name: Convert build files to APK and upload to Github Artifacts
on:
  pull_request:
    branches: [master]
  push:
    branches: [master, apk]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v2
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: Final-apks
        path: my-apks/ # Should be same as "output-folder-path"
